/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanabara
 */
public class telaSorteio extends javax.swing.JFrame {

    /**
     * Creates new form telaSorteio
     */
    public telaSorteio() {
        initComponents();
        lblFrase.setText("<html>Estou pensando em um número entre <b>1 e 5</b>. Tente adivinhar que valor é esse.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panPalpite = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTent = new javax.swing.JLabel();
        lblAcert = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(315, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase do Gênio");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFrase.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblFrase.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel3.setText("Valor");

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPalpiteLayout = new javax.swing.GroupLayout(panPalpite);
        panPalpite.setLayout(panPalpiteLayout);
        panPalpiteLayout.setHorizontalGroup(
            panPalpiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPalpiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panPalpiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPalpite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValor))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panPalpiteLayout.setVerticalGroup(
            panPalpiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPalpiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPalpiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPalpite)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setText("Tentativas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel5.setText("Acertos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel6.setText("Erros");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        lblTent.setText("0");
        getContentPane().add(lblTent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 20, -1));

        lblAcert.setText("0");
        getContentPane().add(lblAcert, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 20, -1));

        lblErros.setText("0");
        getContentPane().add(lblErros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        
        int tentativa = Integer.parseInt(lblTent.getText());
        int erro = Integer.parseInt(lblErros.getText());
        int acerto = Integer.parseInt(lblAcert.getText());
        int num = Integer.parseInt(txtValor.getValue().toString());
      if(num >= 1 && num <= 5){
        double rand = 1 + Math.random() * (5);
        int pensamento = (int) rand; // Também pode usar Math.floor
        if(num == pensamento){
           String frase =  "<html>ACERTOU!</html>";
           tentativa++;
           acerto++;
           lblFrase.setText(frase);
        }else{
           String frase = "<html>ERROU! Pensei em " + pensamento + "</html>";
           tentativa++;
           erro++;
           lblFrase.setText(frase);
        }
        //String frase = (num == pensamento)?"<html>ACERTOU!</html>"  :"<html>ERROU! Pensei em " + pensamento + "</html>";
           lblTent.setText(Integer.toString(tentativa));
           lblAcert.setText(Integer.toString(acerto));
           lblErros.setText(Integer.toString(erro));
        lblFrase.setFont(new Font("Arial Black", Font.BOLD, 18));
      }else{
          JOptionPane.showMessageDialog(null, "Escolha um número entre 1 e 5");
      }
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaSorteio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAcert;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblTent;
    private javax.swing.JPanel panPalpite;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
